  
name        = "fftpack"
description = "A package of fortran subprograms for the fast fourier transform of periodic and other symmetric sequences"
homepage    = "http://www.netlib.org/fftpack/"
version     = "4.0.0"
license     = "Public Domain"
author      = "Paul N. Swarztrauber"
maintainer  = "@fortran-lang"
copyright   = "Copyright 1985 National Center for Atmospheric Research, Boulder, CO"
categories  = ["Fast Fourier Transform"]
keywords    = ["netlib", "fftpack", "fft"]

[build]
auto-executables = false
auto-tests = false
auto-examples = false

# Original test
[[test]]
name = "tstfft"
source-dir = "test"
main = "tstfft.f"

# `fftpack` fft routines
[[test]]
name = "fftpack_zfft"
source-dir = "test"
main = "test_fftpack_zfft.f90"

[[test]]
name = "fftpack_fft"
source-dir = "test"
main = "test_fftpack_fft.f90"

[[test]]
name = "fftpack_ifft"
source-dir = "test"
main = "test_fftpack_ifft.f90"

[[test]]
name = "fftpack_dfft"
source-dir = "test"
main = "test_fftpack_dfft.f90"

[[test]]
name = "fftpack_rfft"
source-dir = "test"
main = "test_fftpack_rfft.f90"

[[test]]
name = "fftpack_irfft"
source-dir = "test"
main = "test_fftpack_irfft.f90"

# `fftpack` utility routines
[[test]]
name = "fftpack_fftshift"
source-dir = "test"
main = "test_fftpack_fftshift.f90"

[[test]]
name = "fftpack_ifftshift"
source-dir = "test"
main = "test_fftpack_ifftshift.f90"
